name: Update Data Workflow

on:
  schedule:
    - cron: '0 10 * * *' # Run every day at 10:00 UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_NAME: github-actions
      GIT_COMMITTER_EMAIL: github-actions@github.com
      GIT_AUTHOR_NAME: github-actions
      GIT_AUTHOR_EMAIL: github-actions@github.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'

      - name: Install dependencies
        run: |
          pip install pandas gspread oauth2client

      - name: Write credentials to file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > omoku-analysis-cred_key.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run the update script
        run: python update_data.py

      - name: Commit and push updates
        run: |
          git config user.name ${{ env.GIT_COMMITTER_NAME }}
          git config user.email ${{ env.GIT_COMMITTER_EMAIL }}
          git add .
          git commit -m "Update data"
          git push https://${{ secrets.PAT }}@github.com/Azaya89/omoku-analysis main
